- name: Create WordPress database
  mysql_db: name={{ wp_db_name }} state=present

- name: Create WordPress database user
  mysql_user: name={{ wp_db_user }} password={{ wp_db_password }} priv={{ wp_db_name }}.*:ALL host='localhost' state=present

- name: download wordpress
  get_url:
     url: "{{ download_url }}"
     dest: "/tmp/latest.tar.gz"

- name: creating dir for wordpress
  file:
     path: "{{ wpdirectory }}"
     state: "directory"
     owner: "nginx"
     group: "nginx"

- name: config firewall
  shell: "firewall-cmd --permanent --zone=public --add-service=http && firewall-cmd --reload"

- name: disable setenforce
  shell: "setenforce permissive"

- name: unpack wordpress installation
  shell: "tar -xvf /tmp/latest.tar.gz -C {{ wpdirectory }} && chown -R nginx:nginx {{ wpdirectory }}"

- name: Copy WordPress config file
  template: src=wp-config.php dest=/usr/share/nginx/html/wordpress/ force=no

#- name: Copy sample config file {{ wpdirectory }}
 # command: mv "{{ wpdirectory }}"/wordpress/wp-config-sample.php "{{ wpdirectory }}"/wordpress/wp-config.php 




